<a href="https://colab.research.google.com/github/trinhvanypro1/Data-Analyst/blob/master/NhanDangChuVietTay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
import matplotlib.pyplot as plt
import random
from keras.datasets import mnist
from keras.models import Sequential
from keras.utils import np_utils
from keras.layers.core import Dense, Activation

In [25]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [23]:
x_train=x_train.reshape(60000,784)
x_train=x_train.astype('float32')
x_train/=255

In [24]:
x_test=x_test.reshape(10000,784)
x_test=x_test.astype('float32')
x_test/=255

In [26]:
nb_class=10
y_train=np_utils.to_categorical(y_train,nb_class)
y_test=np_utils.to_categorical(y_test,nb_class)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
